package com.sinapsistech.taxiWeb.model;

// Generated Feb 9, 2015 11:05:15 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Carrera generated by hbm2java
 */
@Entity
@Table(name = "carrera"
      , schema = "public")
public class Carrera implements java.io.Serializable
{

   private int idCarrera;
   private Compania compania;
   private Tarifa tarifa;
   private Vehiculo vehiculo;
   private String origen;
   private String destino;
   private Date fecha;
   private String observaciones;
   private Date fechaReg;
   private String usuarioReg;
   private Date fechaMod;
   private String usuarioMod;
   private Date fechaBorrado;
   private String usuarioBorrado;
   private Set<Transaccion> transaccions = new HashSet<Transaccion>(0);

   public Carrera()
   {
   }

   public Carrera(int idCarrera, Compania compania, Tarifa tarifa, Vehiculo vehiculo, String origen, Date fecha)
   {
      this.idCarrera = idCarrera;
      this.compania = compania;
      this.tarifa = tarifa;
      this.vehiculo = vehiculo;
      this.origen = origen;
      this.fecha = fecha;
   }

   public Carrera(int idCarrera, Compania compania, Tarifa tarifa, Vehiculo vehiculo, String origen, String destino, Date fecha, String observaciones, Date fechaReg, String usuarioReg, Date fechaMod, String usuarioMod, Date fechaBorrado, String usuarioBorrado, Set<Transaccion> transaccions)
   {
      this.idCarrera = idCarrera;
      this.compania = compania;
      this.tarifa = tarifa;
      this.vehiculo = vehiculo;
      this.origen = origen;
      this.destino = destino;
      this.fecha = fecha;
      this.observaciones = observaciones;
      this.fechaReg = fechaReg;
      this.usuarioReg = usuarioReg;
      this.fechaMod = fechaMod;
      this.usuarioMod = usuarioMod;
      this.fechaBorrado = fechaBorrado;
      this.usuarioBorrado = usuarioBorrado;
      this.transaccions = transaccions;
   }

   @Id
   @Column(name = "id_carrera", unique = true, nullable = false)
   public int getIdCarrera()
   {
      return this.idCarrera;
   }

   public void setIdCarrera(int idCarrera)
   {
      this.idCarrera = idCarrera;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "id_cia", nullable = false)
   public Compania getCompania()
   {
      return this.compania;
   }

   public void setCompania(Compania compania)
   {
      this.compania = compania;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "id_tarifa", nullable = false)
   public Tarifa getTarifa()
   {
      return this.tarifa;
   }

   public void setTarifa(Tarifa tarifa)
   {
      this.tarifa = tarifa;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "id_vehiculo", nullable = false)
   public Vehiculo getVehiculo()
   {
      return this.vehiculo;
   }

   public void setVehiculo(Vehiculo vehiculo)
   {
      this.vehiculo = vehiculo;
   }

   @Column(name = "origen", nullable = false, length = 200)
   public String getOrigen()
   {
      return this.origen;
   }

   public void setOrigen(String origen)
   {
      this.origen = origen;
   }

   @Column(name = "destino", length = 200)
   public String getDestino()
   {
      return this.destino;
   }

   public void setDestino(String destino)
   {
      this.destino = destino;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha", nullable = false, length = 29)
   public Date getFecha()
   {
      return this.fecha;
   }

   public void setFecha(Date fecha)
   {
      this.fecha = fecha;
   }

   @Column(name = "observaciones", length = 200)
   public String getObservaciones()
   {
      return this.observaciones;
   }

   public void setObservaciones(String observaciones)
   {
      this.observaciones = observaciones;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_reg", length = 29)
   public Date getFechaReg()
   {
      return this.fechaReg;
   }

   public void setFechaReg(Date fechaReg)
   {
      this.fechaReg = fechaReg;
   }

   @Column(name = "usuario_reg", length = 30)
   public String getUsuarioReg()
   {
      return this.usuarioReg;
   }

   public void setUsuarioReg(String usuarioReg)
   {
      this.usuarioReg = usuarioReg;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_mod", length = 29)
   public Date getFechaMod()
   {
      return this.fechaMod;
   }

   public void setFechaMod(Date fechaMod)
   {
      this.fechaMod = fechaMod;
   }

   @Column(name = "usuario_mod", length = 30)
   public String getUsuarioMod()
   {
      return this.usuarioMod;
   }

   public void setUsuarioMod(String usuarioMod)
   {
      this.usuarioMod = usuarioMod;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_borrado", length = 29)
   public Date getFechaBorrado()
   {
      return this.fechaBorrado;
   }

   public void setFechaBorrado(Date fechaBorrado)
   {
      this.fechaBorrado = fechaBorrado;
   }

   @Column(name = "usuario_borrado", length = 30)
   public String getUsuarioBorrado()
   {
      return this.usuarioBorrado;
   }

   public void setUsuarioBorrado(String usuarioBorrado)
   {
      this.usuarioBorrado = usuarioBorrado;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "carrera")
   public Set<Transaccion> getTransaccions()
   {
      return this.transaccions;
   }

   public void setTransaccions(Set<Transaccion> transaccions)
   {
      this.transaccions = transaccions;
   }

}
