package com.sinapsistech.taxiWeb.model;

// Generated Feb 9, 2015 11:05:15 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Compania generated by hbm2java
 */
@Entity
@Table(name = "compania"
      , schema = "public")
public class Compania implements java.io.Serializable
{

   private int idCia;
   private String nombreCorto;
   private String nombreLargo;
   private Date fechaInicioOperaciones;
   private String flagEstado;
   private Date fechaReg;
   private String usuarioReg;
   private Date fechaMod;
   private String usuarioMod;
   private Date fechaBorrado;
   private String usuarioBorrado;
   private Set<DetallaPersonaServicio> detallaPersonaServicios = new HashSet<DetallaPersonaServicio>(0);
   private Set<Parqueo> parqueos = new HashSet<Parqueo>(0);
   private Set<VehiculoParqueo> vehiculoParqueos = new HashSet<VehiculoParqueo>(0);
   private Set<VehiculoPersona> vehiculoPersonas = new HashSet<VehiculoPersona>(0);
   private Set<PersonaServicio> personaServicios = new HashSet<PersonaServicio>(0);
   private Set<Tarifa> tarifas = new HashSet<Tarifa>(0);
   private Set<Persona> personas = new HashSet<Persona>(0);
   private Set<Vehiculo> vehiculos = new HashSet<Vehiculo>(0);
   private Set<VehiculoAfiliacion> vehiculoAfiliacions = new HashSet<VehiculoAfiliacion>(0);
   private Set<Carrera> carreras = new HashSet<Carrera>(0);
   private Set<Transaccion> transaccions = new HashSet<Transaccion>(0);
   private Set<Usuario> usuarios = new HashSet<Usuario>(0);
   private Set<Servicio> servicios = new HashSet<Servicio>(0);
   private Set<TipoTransaccion> tipoTransaccions = new HashSet<TipoTransaccion>(0);

   public Compania()
   {
   }

   public Compania(int idCia, String nombreCorto, String nombreLargo)
   {
      this.idCia = idCia;
      this.nombreCorto = nombreCorto;
      this.nombreLargo = nombreLargo;
   }

   public Compania(int idCia, String nombreCorto, String nombreLargo, Date fechaInicioOperaciones, String flagEstado, Date fechaReg, String usuarioReg, Date fechaMod, String usuarioMod, Date fechaBorrado, String usuarioBorrado, Set<DetallaPersonaServicio> detallaPersonaServicios, Set<Parqueo> parqueos, Set<VehiculoParqueo> vehiculoParqueos, Set<VehiculoPersona> vehiculoPersonas, Set<PersonaServicio> personaServicios, Set<Tarifa> tarifas, Set<Persona> personas, Set<Vehiculo> vehiculos, Set<VehiculoAfiliacion> vehiculoAfiliacions, Set<Carrera> carreras, Set<Transaccion> transaccions, Set<Usuario> usuarios, Set<Servicio> servicios, Set<TipoTransaccion> tipoTransaccions)
   {
      this.idCia = idCia;
      this.nombreCorto = nombreCorto;
      this.nombreLargo = nombreLargo;
      this.fechaInicioOperaciones = fechaInicioOperaciones;
      this.flagEstado = flagEstado;
      this.fechaReg = fechaReg;
      this.usuarioReg = usuarioReg;
      this.fechaMod = fechaMod;
      this.usuarioMod = usuarioMod;
      this.fechaBorrado = fechaBorrado;
      this.usuarioBorrado = usuarioBorrado;
      this.detallaPersonaServicios = detallaPersonaServicios;
      this.parqueos = parqueos;
      this.vehiculoParqueos = vehiculoParqueos;
      this.vehiculoPersonas = vehiculoPersonas;
      this.personaServicios = personaServicios;
      this.tarifas = tarifas;
      this.personas = personas;
      this.vehiculos = vehiculos;
      this.vehiculoAfiliacions = vehiculoAfiliacions;
      this.carreras = carreras;
      this.transaccions = transaccions;
      this.usuarios = usuarios;
      this.servicios = servicios;
      this.tipoTransaccions = tipoTransaccions;
   }

   @Id
   @Column(name = "id_cia", unique = true, nullable = false)
   public int getIdCia()
   {
      return this.idCia;
   }

   public void setIdCia(int idCia)
   {
      this.idCia = idCia;
   }

   @Column(name = "nombre_corto", nullable = false, length = 20)
   public String getNombreCorto()
   {
      return this.nombreCorto;
   }

   public void setNombreCorto(String nombreCorto)
   {
      this.nombreCorto = nombreCorto;
   }

   @Column(name = "nombre_largo", nullable = false, length = 200)
   public String getNombreLargo()
   {
      return this.nombreLargo;
   }

   public void setNombreLargo(String nombreLargo)
   {
      this.nombreLargo = nombreLargo;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_inicio_operaciones", length = 29)
   public Date getFechaInicioOperaciones()
   {
      return this.fechaInicioOperaciones;
   }

   public void setFechaInicioOperaciones(Date fechaInicioOperaciones)
   {
      this.fechaInicioOperaciones = fechaInicioOperaciones;
   }

   @Column(name = "flag_estado", length = 2)
   public String getFlagEstado()
   {
      return this.flagEstado;
   }

   public void setFlagEstado(String flagEstado)
   {
      this.flagEstado = flagEstado;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_reg", length = 29)
   public Date getFechaReg()
   {
      return this.fechaReg;
   }

   public void setFechaReg(Date fechaReg)
   {
      this.fechaReg = fechaReg;
   }

   @Column(name = "usuario_reg", length = 30)
   public String getUsuarioReg()
   {
      return this.usuarioReg;
   }

   public void setUsuarioReg(String usuarioReg)
   {
      this.usuarioReg = usuarioReg;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_mod", length = 29)
   public Date getFechaMod()
   {
      return this.fechaMod;
   }

   public void setFechaMod(Date fechaMod)
   {
      this.fechaMod = fechaMod;
   }

   @Column(name = "usuario_mod", length = 30)
   public String getUsuarioMod()
   {
      return this.usuarioMod;
   }

   public void setUsuarioMod(String usuarioMod)
   {
      this.usuarioMod = usuarioMod;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_borrado", length = 29)
   public Date getFechaBorrado()
   {
      return this.fechaBorrado;
   }

   public void setFechaBorrado(Date fechaBorrado)
   {
      this.fechaBorrado = fechaBorrado;
   }

   @Column(name = "usuario_borrado", length = 30)
   public String getUsuarioBorrado()
   {
      return this.usuarioBorrado;
   }

   public void setUsuarioBorrado(String usuarioBorrado)
   {
      this.usuarioBorrado = usuarioBorrado;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "compania")
   public Set<DetallaPersonaServicio> getDetallaPersonaServicios()
   {
      return this.detallaPersonaServicios;
   }

   public void setDetallaPersonaServicios(Set<DetallaPersonaServicio> detallaPersonaServicios)
   {
      this.detallaPersonaServicios = detallaPersonaServicios;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "compania")
   public Set<Parqueo> getParqueos()
   {
      return this.parqueos;
   }

   public void setParqueos(Set<Parqueo> parqueos)
   {
      this.parqueos = parqueos;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "compania")
   public Set<VehiculoParqueo> getVehiculoParqueos()
   {
      return this.vehiculoParqueos;
   }

   public void setVehiculoParqueos(Set<VehiculoParqueo> vehiculoParqueos)
   {
      this.vehiculoParqueos = vehiculoParqueos;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "compania")
   public Set<VehiculoPersona> getVehiculoPersonas()
   {
      return this.vehiculoPersonas;
   }

   public void setVehiculoPersonas(Set<VehiculoPersona> vehiculoPersonas)
   {
      this.vehiculoPersonas = vehiculoPersonas;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "compania")
   public Set<PersonaServicio> getPersonaServicios()
   {
      return this.personaServicios;
   }

   public void setPersonaServicios(Set<PersonaServicio> personaServicios)
   {
      this.personaServicios = personaServicios;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "compania")
   public Set<Tarifa> getTarifas()
   {
      return this.tarifas;
   }

   public void setTarifas(Set<Tarifa> tarifas)
   {
      this.tarifas = tarifas;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "compania")
   public Set<Persona> getPersonas()
   {
      return this.personas;
   }

   public void setPersonas(Set<Persona> personas)
   {
      this.personas = personas;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "compania")
   public Set<Vehiculo> getVehiculos()
   {
      return this.vehiculos;
   }

   public void setVehiculos(Set<Vehiculo> vehiculos)
   {
      this.vehiculos = vehiculos;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "compania")
   public Set<VehiculoAfiliacion> getVehiculoAfiliacions()
   {
      return this.vehiculoAfiliacions;
   }

   public void setVehiculoAfiliacions(Set<VehiculoAfiliacion> vehiculoAfiliacions)
   {
      this.vehiculoAfiliacions = vehiculoAfiliacions;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "compania")
   public Set<Carrera> getCarreras()
   {
      return this.carreras;
   }

   public void setCarreras(Set<Carrera> carreras)
   {
      this.carreras = carreras;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "compania")
   public Set<Transaccion> getTransaccions()
   {
      return this.transaccions;
   }

   public void setTransaccions(Set<Transaccion> transaccions)
   {
      this.transaccions = transaccions;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "compania")
   public Set<Usuario> getUsuarios()
   {
      return this.usuarios;
   }

   public void setUsuarios(Set<Usuario> usuarios)
   {
      this.usuarios = usuarios;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "compania")
   public Set<Servicio> getServicios()
   {
      return this.servicios;
   }

   public void setServicios(Set<Servicio> servicios)
   {
      this.servicios = servicios;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "compania")
   public Set<TipoTransaccion> getTipoTransaccions()
   {
      return this.tipoTransaccions;
   }

   public void setTipoTransaccions(Set<TipoTransaccion> tipoTransaccions)
   {
      this.tipoTransaccions = tipoTransaccions;
   }

}
