package com.sinapsistech.taxiWeb.model;

// Generated Feb 9, 2015 11:05:15 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Parqueo generated by hbm2java
 */
@Entity
@Table(name = "parqueo"
      , schema = "public")
public class Parqueo implements java.io.Serializable
{

   private int idParqueo;
   private Compania compania;
   private String direccion;
   private int idCiudad;
   private String latitud;
   private String longitud;
   private String flagEstado;
   private Date fechaReg;
   private String usuarioReg;
   private Date fechaMod;
   private String usuarioMod;
   private Date fechaBorrado;
   private String usuarioBorrado;
   private Set<VehiculoParqueo> vehiculoParqueos = new HashSet<VehiculoParqueo>(0);

   public Parqueo()
   {
   }

   public Parqueo(int idParqueo, Compania compania, String direccion, int idCiudad, String latitud, String longitud)
   {
      this.idParqueo = idParqueo;
      this.compania = compania;
      this.direccion = direccion;
      this.idCiudad = idCiudad;
      this.latitud = latitud;
      this.longitud = longitud;
   }

   public Parqueo(int idParqueo, Compania compania, String direccion, int idCiudad, String latitud, String longitud, String flagEstado, Date fechaReg, String usuarioReg, Date fechaMod, String usuarioMod, Date fechaBorrado, String usuarioBorrado, Set<VehiculoParqueo> vehiculoParqueos)
   {
      this.idParqueo = idParqueo;
      this.compania = compania;
      this.direccion = direccion;
      this.idCiudad = idCiudad;
      this.latitud = latitud;
      this.longitud = longitud;
      this.flagEstado = flagEstado;
      this.fechaReg = fechaReg;
      this.usuarioReg = usuarioReg;
      this.fechaMod = fechaMod;
      this.usuarioMod = usuarioMod;
      this.fechaBorrado = fechaBorrado;
      this.usuarioBorrado = usuarioBorrado;
      this.vehiculoParqueos = vehiculoParqueos;
   }

   @Id
   @Column(name = "id_parqueo", unique = true, nullable = false)
   public int getIdParqueo()
   {
      return this.idParqueo;
   }

   public void setIdParqueo(int idParqueo)
   {
      this.idParqueo = idParqueo;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "id_cia", nullable = false)
   public Compania getCompania()
   {
      return this.compania;
   }

   public void setCompania(Compania compania)
   {
      this.compania = compania;
   }

   @Column(name = "direccion", nullable = false, length = 200)
   public String getDireccion()
   {
      return this.direccion;
   }

   public void setDireccion(String direccion)
   {
      this.direccion = direccion;
   }

   @Column(name = "id_ciudad", nullable = false)
   public int getIdCiudad()
   {
      return this.idCiudad;
   }

   public void setIdCiudad(int idCiudad)
   {
      this.idCiudad = idCiudad;
   }

   @Column(name = "latitud", nullable = false, length = 20)
   public String getLatitud()
   {
      return this.latitud;
   }

   public void setLatitud(String latitud)
   {
      this.latitud = latitud;
   }

   @Column(name = "longitud", nullable = false, length = 20)
   public String getLongitud()
   {
      return this.longitud;
   }

   public void setLongitud(String longitud)
   {
      this.longitud = longitud;
   }

   @Column(name = "flag_estado", length = 2)
   public String getFlagEstado()
   {
      return this.flagEstado;
   }

   public void setFlagEstado(String flagEstado)
   {
      this.flagEstado = flagEstado;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_reg", length = 29)
   public Date getFechaReg()
   {
      return this.fechaReg;
   }

   public void setFechaReg(Date fechaReg)
   {
      this.fechaReg = fechaReg;
   }

   @Column(name = "usuario_reg", length = 30)
   public String getUsuarioReg()
   {
      return this.usuarioReg;
   }

   public void setUsuarioReg(String usuarioReg)
   {
      this.usuarioReg = usuarioReg;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_mod", length = 29)
   public Date getFechaMod()
   {
      return this.fechaMod;
   }

   public void setFechaMod(Date fechaMod)
   {
      this.fechaMod = fechaMod;
   }

   @Column(name = "usuario_mod", length = 30)
   public String getUsuarioMod()
   {
      return this.usuarioMod;
   }

   public void setUsuarioMod(String usuarioMod)
   {
      this.usuarioMod = usuarioMod;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_borrado", length = 29)
   public Date getFechaBorrado()
   {
      return this.fechaBorrado;
   }

   public void setFechaBorrado(Date fechaBorrado)
   {
      this.fechaBorrado = fechaBorrado;
   }

   @Column(name = "usuario_borrado", length = 30)
   public String getUsuarioBorrado()
   {
      return this.usuarioBorrado;
   }

   public void setUsuarioBorrado(String usuarioBorrado)
   {
      this.usuarioBorrado = usuarioBorrado;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "parqueo")
   public Set<VehiculoParqueo> getVehiculoParqueos()
   {
      return this.vehiculoParqueos;
   }

   public void setVehiculoParqueos(Set<VehiculoParqueo> vehiculoParqueos)
   {
      this.vehiculoParqueos = vehiculoParqueos;
   }

}
