package com.sinapsistech.taxiWeb.model;

// Generated Feb 9, 2015 11:05:15 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PersonaServicio generated by hbm2java
 */
@Entity
@Table(name = "persona_servicio"
      , schema = "public")
public class PersonaServicio implements java.io.Serializable
{

   private int idPersonaServicio;
   private Compania compania;
   private Persona persona;
   private Servicio servicio;
   private Tarifa tarifa;
   private Date fechaInicio;
   private Date fechaFin;
   private String descripcion;
   private boolean flagSabadoDomingo;
   private String origen;
   private String desitino;
   private String flagEstado;
   private Date fechaReg;
   private String usuarioReg;
   private Date fechaMod;
   private String usuarioMod;
   private Date fechaBorrado;
   private String usuarioBorrado;
   private Set<DetallaPersonaServicio> detallaPersonaServicios = new HashSet<DetallaPersonaServicio>(0);
   private Set<Transaccion> transaccions = new HashSet<Transaccion>(0);

   public PersonaServicio()
   {
   }

   public PersonaServicio(int idPersonaServicio, Compania compania, Persona persona, Servicio servicio, Tarifa tarifa, Date fechaInicio, String descripcion, boolean flagSabadoDomingo, String origen, String desitino)
   {
      this.idPersonaServicio = idPersonaServicio;
      this.compania = compania;
      this.persona = persona;
      this.servicio = servicio;
      this.tarifa = tarifa;
      this.fechaInicio = fechaInicio;
      this.descripcion = descripcion;
      this.flagSabadoDomingo = flagSabadoDomingo;
      this.origen = origen;
      this.desitino = desitino;
   }

   public PersonaServicio(int idPersonaServicio, Compania compania, Persona persona, Servicio servicio, Tarifa tarifa, Date fechaInicio, Date fechaFin, String descripcion, boolean flagSabadoDomingo, String origen, String desitino, String flagEstado, Date fechaReg, String usuarioReg, Date fechaMod, String usuarioMod, Date fechaBorrado, String usuarioBorrado, Set<DetallaPersonaServicio> detallaPersonaServicios, Set<Transaccion> transaccions)
   {
      this.idPersonaServicio = idPersonaServicio;
      this.compania = compania;
      this.persona = persona;
      this.servicio = servicio;
      this.tarifa = tarifa;
      this.fechaInicio = fechaInicio;
      this.fechaFin = fechaFin;
      this.descripcion = descripcion;
      this.flagSabadoDomingo = flagSabadoDomingo;
      this.origen = origen;
      this.desitino = desitino;
      this.flagEstado = flagEstado;
      this.fechaReg = fechaReg;
      this.usuarioReg = usuarioReg;
      this.fechaMod = fechaMod;
      this.usuarioMod = usuarioMod;
      this.fechaBorrado = fechaBorrado;
      this.usuarioBorrado = usuarioBorrado;
      this.detallaPersonaServicios = detallaPersonaServicios;
      this.transaccions = transaccions;
   }

   @Id
   @Column(name = "id_persona_servicio", unique = true, nullable = false)
   public int getIdPersonaServicio()
   {
      return this.idPersonaServicio;
   }

   public void setIdPersonaServicio(int idPersonaServicio)
   {
      this.idPersonaServicio = idPersonaServicio;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "id_cia", nullable = false)
   public Compania getCompania()
   {
      return this.compania;
   }

   public void setCompania(Compania compania)
   {
      this.compania = compania;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "id_persona", nullable = false)
   public Persona getPersona()
   {
      return this.persona;
   }

   public void setPersona(Persona persona)
   {
      this.persona = persona;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "id_servicio", nullable = false)
   public Servicio getServicio()
   {
      return this.servicio;
   }

   public void setServicio(Servicio servicio)
   {
      this.servicio = servicio;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "id_tarifa", nullable = false)
   public Tarifa getTarifa()
   {
      return this.tarifa;
   }

   public void setTarifa(Tarifa tarifa)
   {
      this.tarifa = tarifa;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_inicio", nullable = false, length = 29)
   public Date getFechaInicio()
   {
      return this.fechaInicio;
   }

   public void setFechaInicio(Date fechaInicio)
   {
      this.fechaInicio = fechaInicio;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_fin", length = 29)
   public Date getFechaFin()
   {
      return this.fechaFin;
   }

   public void setFechaFin(Date fechaFin)
   {
      this.fechaFin = fechaFin;
   }

   @Column(name = "descripcion", nullable = false, length = 200)
   public String getDescripcion()
   {
      return this.descripcion;
   }

   public void setDescripcion(String descripcion)
   {
      this.descripcion = descripcion;
   }

   @Column(name = "flag_sabado_domingo", nullable = false)
   public boolean isFlagSabadoDomingo()
   {
      return this.flagSabadoDomingo;
   }

   public void setFlagSabadoDomingo(boolean flagSabadoDomingo)
   {
      this.flagSabadoDomingo = flagSabadoDomingo;
   }

   @Column(name = "origen", nullable = false, length = 200)
   public String getOrigen()
   {
      return this.origen;
   }

   public void setOrigen(String origen)
   {
      this.origen = origen;
   }

   @Column(name = "desitino", nullable = false, length = 200)
   public String getDesitino()
   {
      return this.desitino;
   }

   public void setDesitino(String desitino)
   {
      this.desitino = desitino;
   }

   @Column(name = "flag_estado", length = 2)
   public String getFlagEstado()
   {
      return this.flagEstado;
   }

   public void setFlagEstado(String flagEstado)
   {
      this.flagEstado = flagEstado;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_reg", length = 29)
   public Date getFechaReg()
   {
      return this.fechaReg;
   }

   public void setFechaReg(Date fechaReg)
   {
      this.fechaReg = fechaReg;
   }

   @Column(name = "usuario_reg", length = 30)
   public String getUsuarioReg()
   {
      return this.usuarioReg;
   }

   public void setUsuarioReg(String usuarioReg)
   {
      this.usuarioReg = usuarioReg;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_mod", length = 29)
   public Date getFechaMod()
   {
      return this.fechaMod;
   }

   public void setFechaMod(Date fechaMod)
   {
      this.fechaMod = fechaMod;
   }

   @Column(name = "usuario_mod", length = 30)
   public String getUsuarioMod()
   {
      return this.usuarioMod;
   }

   public void setUsuarioMod(String usuarioMod)
   {
      this.usuarioMod = usuarioMod;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_borrado", length = 29)
   public Date getFechaBorrado()
   {
      return this.fechaBorrado;
   }

   public void setFechaBorrado(Date fechaBorrado)
   {
      this.fechaBorrado = fechaBorrado;
   }

   @Column(name = "usuario_borrado", length = 30)
   public String getUsuarioBorrado()
   {
      return this.usuarioBorrado;
   }

   public void setUsuarioBorrado(String usuarioBorrado)
   {
      this.usuarioBorrado = usuarioBorrado;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "personaServicio")
   public Set<DetallaPersonaServicio> getDetallaPersonaServicios()
   {
      return this.detallaPersonaServicios;
   }

   public void setDetallaPersonaServicios(Set<DetallaPersonaServicio> detallaPersonaServicios)
   {
      this.detallaPersonaServicios = detallaPersonaServicios;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "personaServicio")
   public Set<Transaccion> getTransaccions()
   {
      return this.transaccions;
   }

   public void setTransaccions(Set<Transaccion> transaccions)
   {
      this.transaccions = transaccions;
   }

}
