package com.sinapsistech.taxiWeb.model;

// Generated Feb 9, 2015 11:05:15 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Persona generated by hbm2java
 */
@Entity
@Table(name = "persona"
      , schema = "public")
public class Persona implements java.io.Serializable
{

   private int idPersona;
   private Compania compania;
   private TipoPersona tipoPersona;
   private String nombre;
   private String apellidoPaterno;
   private String apellidoMaterno;
   private String direccion;
   private int telefono1;
   private int telefono2;
   private int documentoIdentidad;
   private Date fechaNacimiento;
   private Integer numeroRegistro;
   private String flagEstado;
   private Date fechaReg;
   private String usuarioReg;
   private Date fechaMod;
   private String usuarioMod;
   private Date fechaBorrado;
   private String usuarioBorrado;
   private Set<VehiculoPersona> vehiculoPersonasForIdChofer = new HashSet<VehiculoPersona>(0);
   private Set<VehiculoPersona> vehiculoPersonasForIdPersona = new HashSet<VehiculoPersona>(0);
   private Set<Transaccion> transaccions = new HashSet<Transaccion>(0);
   private Set<PersonaServicio> personaServicios = new HashSet<PersonaServicio>(0);
   private Set<VehiculoAfiliacion> vehiculoAfiliacions = new HashSet<VehiculoAfiliacion>(0);

   public Persona()
   {
   }

   public Persona(int idPersona, Compania compania, TipoPersona tipoPersona, String nombre, int telefono1, int telefono2, int documentoIdentidad, Date fechaNacimiento)
   {
      this.idPersona = idPersona;
      this.compania = compania;
      this.tipoPersona = tipoPersona;
      this.nombre = nombre;
      this.telefono1 = telefono1;
      this.telefono2 = telefono2;
      this.documentoIdentidad = documentoIdentidad;
      this.fechaNacimiento = fechaNacimiento;
   }

   public Persona(int idPersona, Compania compania, TipoPersona tipoPersona, String nombre, String apellidoPaterno, String apellidoMaterno, String direccion, int telefono1, int telefono2, int documentoIdentidad, Date fechaNacimiento, Integer numeroRegistro, String flagEstado, Date fechaReg, String usuarioReg, Date fechaMod, String usuarioMod, Date fechaBorrado, String usuarioBorrado, Set<VehiculoPersona> vehiculoPersonasForIdChofer, Set<VehiculoPersona> vehiculoPersonasForIdPersona, Set<Transaccion> transaccions, Set<PersonaServicio> personaServicios, Set<VehiculoAfiliacion> vehiculoAfiliacions)
   {
      this.idPersona = idPersona;
      this.compania = compania;
      this.tipoPersona = tipoPersona;
      this.nombre = nombre;
      this.apellidoPaterno = apellidoPaterno;
      this.apellidoMaterno = apellidoMaterno;
      this.direccion = direccion;
      this.telefono1 = telefono1;
      this.telefono2 = telefono2;
      this.documentoIdentidad = documentoIdentidad;
      this.fechaNacimiento = fechaNacimiento;
      this.numeroRegistro = numeroRegistro;
      this.flagEstado = flagEstado;
      this.fechaReg = fechaReg;
      this.usuarioReg = usuarioReg;
      this.fechaMod = fechaMod;
      this.usuarioMod = usuarioMod;
      this.fechaBorrado = fechaBorrado;
      this.usuarioBorrado = usuarioBorrado;
      this.vehiculoPersonasForIdChofer = vehiculoPersonasForIdChofer;
      this.vehiculoPersonasForIdPersona = vehiculoPersonasForIdPersona;
      this.transaccions = transaccions;
      this.personaServicios = personaServicios;
      this.vehiculoAfiliacions = vehiculoAfiliacions;
   }

   @Id
   @Column(name = "id_persona", unique = true, nullable = false)
   public int getIdPersona()
   {
      return this.idPersona;
   }

   public void setIdPersona(int idPersona)
   {
      this.idPersona = idPersona;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "id_cia", nullable = false)
   public Compania getCompania()
   {
      return this.compania;
   }

   public void setCompania(Compania compania)
   {
      this.compania = compania;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "id_tipo_persona", nullable = false)
   public TipoPersona getTipoPersona()
   {
      return this.tipoPersona;
   }

   public void setTipoPersona(TipoPersona tipoPersona)
   {
      this.tipoPersona = tipoPersona;
   }

   @Column(name = "nombre", nullable = false, length = 20)
   public String getNombre()
   {
      return this.nombre;
   }

   public void setNombre(String nombre)
   {
      this.nombre = nombre;
   }

   @Column(name = "apellido_paterno", length = 20)
   public String getApellidoPaterno()
   {
      return this.apellidoPaterno;
   }

   public void setApellidoPaterno(String apellidoPaterno)
   {
      this.apellidoPaterno = apellidoPaterno;
   }

   @Column(name = "apellido_materno", length = 20)
   public String getApellidoMaterno()
   {
      return this.apellidoMaterno;
   }

   public void setApellidoMaterno(String apellidoMaterno)
   {
      this.apellidoMaterno = apellidoMaterno;
   }

   @Column(name = "direccion", length = 200)
   public String getDireccion()
   {
      return this.direccion;
   }

   public void setDireccion(String direccion)
   {
      this.direccion = direccion;
   }

   @Column(name = "telefono1", nullable = false)
   public int getTelefono1()
   {
      return this.telefono1;
   }

   public void setTelefono1(int telefono1)
   {
      this.telefono1 = telefono1;
   }

   @Column(name = "telefono2", nullable = false)
   public int getTelefono2()
   {
      return this.telefono2;
   }

   public void setTelefono2(int telefono2)
   {
      this.telefono2 = telefono2;
   }

   @Column(name = "documento_identidad", nullable = false)
   public int getDocumentoIdentidad()
   {
      return this.documentoIdentidad;
   }

   public void setDocumentoIdentidad(int documentoIdentidad)
   {
      this.documentoIdentidad = documentoIdentidad;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_nacimiento", nullable = false, length = 29)
   public Date getFechaNacimiento()
   {
      return this.fechaNacimiento;
   }

   public void setFechaNacimiento(Date fechaNacimiento)
   {
      this.fechaNacimiento = fechaNacimiento;
   }

   @Column(name = "numero_registro")
   public Integer getNumeroRegistro()
   {
      return this.numeroRegistro;
   }

   public void setNumeroRegistro(Integer numeroRegistro)
   {
      this.numeroRegistro = numeroRegistro;
   }

   @Column(name = "flag_estado", length = 2)
   public String getFlagEstado()
   {
      return this.flagEstado;
   }

   public void setFlagEstado(String flagEstado)
   {
      this.flagEstado = flagEstado;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_reg", length = 29)
   public Date getFechaReg()
   {
      return this.fechaReg;
   }

   public void setFechaReg(Date fechaReg)
   {
      this.fechaReg = fechaReg;
   }

   @Column(name = "usuario_reg", length = 30)
   public String getUsuarioReg()
   {
      return this.usuarioReg;
   }

   public void setUsuarioReg(String usuarioReg)
   {
      this.usuarioReg = usuarioReg;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_mod", length = 29)
   public Date getFechaMod()
   {
      return this.fechaMod;
   }

   public void setFechaMod(Date fechaMod)
   {
      this.fechaMod = fechaMod;
   }

   @Column(name = "usuario_mod", length = 30)
   public String getUsuarioMod()
   {
      return this.usuarioMod;
   }

   public void setUsuarioMod(String usuarioMod)
   {
      this.usuarioMod = usuarioMod;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_borrado", length = 29)
   public Date getFechaBorrado()
   {
      return this.fechaBorrado;
   }

   public void setFechaBorrado(Date fechaBorrado)
   {
      this.fechaBorrado = fechaBorrado;
   }

   @Column(name = "usuario_borrado", length = 30)
   public String getUsuarioBorrado()
   {
      return this.usuarioBorrado;
   }

   public void setUsuarioBorrado(String usuarioBorrado)
   {
      this.usuarioBorrado = usuarioBorrado;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "personaByIdChofer")
   public Set<VehiculoPersona> getVehiculoPersonasForIdChofer()
   {
      return this.vehiculoPersonasForIdChofer;
   }

   public void setVehiculoPersonasForIdChofer(Set<VehiculoPersona> vehiculoPersonasForIdChofer)
   {
      this.vehiculoPersonasForIdChofer = vehiculoPersonasForIdChofer;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "personaByIdPersona")
   public Set<VehiculoPersona> getVehiculoPersonasForIdPersona()
   {
      return this.vehiculoPersonasForIdPersona;
   }

   public void setVehiculoPersonasForIdPersona(Set<VehiculoPersona> vehiculoPersonasForIdPersona)
   {
      this.vehiculoPersonasForIdPersona = vehiculoPersonasForIdPersona;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "persona")
   public Set<Transaccion> getTransaccions()
   {
      return this.transaccions;
   }

   public void setTransaccions(Set<Transaccion> transaccions)
   {
      this.transaccions = transaccions;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "persona")
   public Set<PersonaServicio> getPersonaServicios()
   {
      return this.personaServicios;
   }

   public void setPersonaServicios(Set<PersonaServicio> personaServicios)
   {
      this.personaServicios = personaServicios;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "persona")
   public Set<VehiculoAfiliacion> getVehiculoAfiliacions()
   {
      return this.vehiculoAfiliacions;
   }

   public void setVehiculoAfiliacions(Set<VehiculoAfiliacion> vehiculoAfiliacions)
   {
      this.vehiculoAfiliacions = vehiculoAfiliacions;
   }

}
