package com.sinapsistech.taxiWeb.model;

// Generated Feb 9, 2015 11:05:15 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Servicio generated by hbm2java
 */
@Entity
@Table(name = "servicio"
      , schema = "public")
public class Servicio implements java.io.Serializable
{

   private int idServicio;
   private Compania compania;
   private String nombre;
   private String descripcion;
   private boolean flagCortecia;
   private String flagEstado;
   private Date fechaReg;
   private String usuarioReg;
   private Date fechaMod;
   private String usuarioMod;
   private Date fechaBorrado;
   private String usuarioBorrado;
   private Set<PersonaServicio> personaServicios = new HashSet<PersonaServicio>(0);

   public Servicio()
   {
   }

   public Servicio(int idServicio, Compania compania, String nombre, String descripcion, boolean flagCortecia)
   {
      this.idServicio = idServicio;
      this.compania = compania;
      this.nombre = nombre;
      this.descripcion = descripcion;
      this.flagCortecia = flagCortecia;
   }

   public Servicio(int idServicio, Compania compania, String nombre, String descripcion, boolean flagCortecia, String flagEstado, Date fechaReg, String usuarioReg, Date fechaMod, String usuarioMod, Date fechaBorrado, String usuarioBorrado, Set<PersonaServicio> personaServicios)
   {
      this.idServicio = idServicio;
      this.compania = compania;
      this.nombre = nombre;
      this.descripcion = descripcion;
      this.flagCortecia = flagCortecia;
      this.flagEstado = flagEstado;
      this.fechaReg = fechaReg;
      this.usuarioReg = usuarioReg;
      this.fechaMod = fechaMod;
      this.usuarioMod = usuarioMod;
      this.fechaBorrado = fechaBorrado;
      this.usuarioBorrado = usuarioBorrado;
      this.personaServicios = personaServicios;
   }

   @Id
   @Column(name = "id_servicio", unique = true, nullable = false)
   public int getIdServicio()
   {
      return this.idServicio;
   }

   public void setIdServicio(int idServicio)
   {
      this.idServicio = idServicio;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "id_cia", nullable = false)
   public Compania getCompania()
   {
      return this.compania;
   }

   public void setCompania(Compania compania)
   {
      this.compania = compania;
   }

   @Column(name = "nombre", nullable = false, length = 50)
   public String getNombre()
   {
      return this.nombre;
   }

   public void setNombre(String nombre)
   {
      this.nombre = nombre;
   }

   @Column(name = "descripcion", nullable = false, length = 200)
   public String getDescripcion()
   {
      return this.descripcion;
   }

   public void setDescripcion(String descripcion)
   {
      this.descripcion = descripcion;
   }

   @Column(name = "flag_cortecia", nullable = false)
   public boolean isFlagCortecia()
   {
      return this.flagCortecia;
   }

   public void setFlagCortecia(boolean flagCortecia)
   {
      this.flagCortecia = flagCortecia;
   }

   @Column(name = "flag_estado", length = 2)
   public String getFlagEstado()
   {
      return this.flagEstado;
   }

   public void setFlagEstado(String flagEstado)
   {
      this.flagEstado = flagEstado;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_reg", length = 29)
   public Date getFechaReg()
   {
      return this.fechaReg;
   }

   public void setFechaReg(Date fechaReg)
   {
      this.fechaReg = fechaReg;
   }

   @Column(name = "usuario_reg", length = 30)
   public String getUsuarioReg()
   {
      return this.usuarioReg;
   }

   public void setUsuarioReg(String usuarioReg)
   {
      this.usuarioReg = usuarioReg;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_mod", length = 29)
   public Date getFechaMod()
   {
      return this.fechaMod;
   }

   public void setFechaMod(Date fechaMod)
   {
      this.fechaMod = fechaMod;
   }

   @Column(name = "usuario_mod", length = 30)
   public String getUsuarioMod()
   {
      return this.usuarioMod;
   }

   public void setUsuarioMod(String usuarioMod)
   {
      this.usuarioMod = usuarioMod;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_borrado", length = 29)
   public Date getFechaBorrado()
   {
      return this.fechaBorrado;
   }

   public void setFechaBorrado(Date fechaBorrado)
   {
      this.fechaBorrado = fechaBorrado;
   }

   @Column(name = "usuario_borrado", length = 30)
   public String getUsuarioBorrado()
   {
      return this.usuarioBorrado;
   }

   public void setUsuarioBorrado(String usuarioBorrado)
   {
      this.usuarioBorrado = usuarioBorrado;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "servicio")
   public Set<PersonaServicio> getPersonaServicios()
   {
      return this.personaServicios;
   }

   public void setPersonaServicios(Set<PersonaServicio> personaServicios)
   {
      this.personaServicios = personaServicios;
   }

}
