package com.sinapsistech.taxiWeb.model;

// Generated Feb 9, 2015 11:05:15 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TipoVehiculo generated by hbm2java
 */
@Entity
@Table(name = "tipo_vehiculo"
      , schema = "public")
public class TipoVehiculo implements java.io.Serializable
{

   private int idTipoVehiculo;
   private String nombre;
   private String flagEstado;
   private Date fechaReg;
   private String usuarioReg;
   private Date fechaMod;
   private String usuarioMod;
   private Date fechaBorrado;
   private String usuarioBorrado;
   private double montoAfiliacion;
   private Set<Vehiculo> vehiculos = new HashSet<Vehiculo>(0);

   public TipoVehiculo()
   {
   }

   public TipoVehiculo(int idTipoVehiculo, String nombre)
   {
      this.idTipoVehiculo = idTipoVehiculo;
      this.nombre = nombre;
   }

   public TipoVehiculo(int idTipoVehiculo, String nombre, String flagEstado, Date fechaReg, String usuarioReg, Date fechaMod, String usuarioMod, Date fechaBorrado, String usuarioBorrado, Set<Vehiculo> vehiculos, double montoAfiliacion)
   {
      this.idTipoVehiculo = idTipoVehiculo;
      this.nombre = nombre;
      this.flagEstado = flagEstado;
      this.fechaReg = fechaReg;
      this.usuarioReg = usuarioReg;
      this.fechaMod = fechaMod;
      this.usuarioMod = usuarioMod;
      this.fechaBorrado = fechaBorrado;
      this.usuarioBorrado = usuarioBorrado;
      this.vehiculos = vehiculos;
      this.montoAfiliacion = montoAfiliacion;
   }

   @Id
   @Column(name = "id_tipo_vehiculo", unique = true, nullable = false)
   public int getIdTipoVehiculo()
   {
      return this.idTipoVehiculo;
   }

   public void setIdTipoVehiculo(int idTipoVehiculo)
   {
      this.idTipoVehiculo = idTipoVehiculo;
   }

   @Column(name = "nombre", nullable = false, length = 20)
   public String getNombre()
   {
      return this.nombre;
   }

   public void setNombre(String nombre)
   {
      this.nombre = nombre;
   }

   @Column(name = "flag_estado", length = 2)
   public String getFlagEstado()
   {
      return this.flagEstado;
   }

   public void setFlagEstado(String flagEstado)
   {
      this.flagEstado = flagEstado;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_reg", length = 29)
   public Date getFechaReg()
   {
      return this.fechaReg;
   }

   public void setFechaReg(Date fechaReg)
   {
      this.fechaReg = fechaReg;
   }

   @Column(name = "usuario_reg", length = 30)
   public String getUsuarioReg()
   {
      return this.usuarioReg;
   }

   public void setUsuarioReg(String usuarioReg)
   {
      this.usuarioReg = usuarioReg;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_mod", length = 29)
   public Date getFechaMod()
   {
      return this.fechaMod;
   }

   public void setFechaMod(Date fechaMod)
   {
      this.fechaMod = fechaMod;
   }

   @Column(name = "usuario_mod", length = 30)
   public String getUsuarioMod()
   {
      return this.usuarioMod;
   }

   public void setUsuarioMod(String usuarioMod)
   {
      this.usuarioMod = usuarioMod;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_borrado", length = 29)
   public Date getFechaBorrado()
   {
      return this.fechaBorrado;
   }

   public void setFechaBorrado(Date fechaBorrado)
   {
      this.fechaBorrado = fechaBorrado;
   }

   @Column(name = "usuario_borrado", length = 30)
   public String getUsuarioBorrado()
   {
      return this.usuarioBorrado;
   }

   public void setUsuarioBorrado(String usuarioBorrado)
   {
      this.usuarioBorrado = usuarioBorrado;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoVehiculo")
   public Set<Vehiculo> getVehiculos()
   {
      return this.vehiculos;
   }

   public void setVehiculos(Set<Vehiculo> vehiculos)
   {
      this.vehiculos = vehiculos;
   }
   @Column(name = "monto_afiliacion", nullable = false, precision = 17, scale = 17)
   public double getMontoAfiliacion()
   {
      return this.montoAfiliacion;
   }

   public void setMontoAfiliacion(double montoAfiliacion)
   {
      this.montoAfiliacion = montoAfiliacion;
   }
}
