package com.sinapsistech.taxiWeb.model;

// Generated Feb 9, 2015 11:05:15 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TipoTransaccion generated by hbm2java
 */
@Entity
@Table(name = "tipo_transaccion"
      , schema = "public")
public class TipoTransaccion implements java.io.Serializable
{

   private int idTipoTransaccion;
   private Compania compania;
   private String nombre;
   private String descripcion;
   private String tipo;
   private String flagEstado;
   private Date fechaReg;
   private String usuarioReg;
   private Date fechaMod;
   private String usuarioMod;
   private Date fechaBorrado;
   private String usuarioBorrado;
   private Set<Transaccion> transaccions = new HashSet<Transaccion>(0);

   public TipoTransaccion()
   {
   }

   public TipoTransaccion(int idTipoTransaccion, Compania compania, String nombre, String descripcion, String tipo)
   {
      this.idTipoTransaccion = idTipoTransaccion;
      this.compania = compania;
      this.nombre = nombre;
      this.descripcion = descripcion;
      this.tipo = tipo;
   }

   public TipoTransaccion(int idTipoTransaccion, Compania compania, String nombre, String descripcion, String tipo, String flagEstado, Date fechaReg, String usuarioReg, Date fechaMod, String usuarioMod, Date fechaBorrado, String usuarioBorrado, Set<Transaccion> transaccions)
   {
      this.idTipoTransaccion = idTipoTransaccion;
      this.compania = compania;
      this.nombre = nombre;
      this.descripcion = descripcion;
      this.tipo = tipo;
      this.flagEstado = flagEstado;
      this.fechaReg = fechaReg;
      this.usuarioReg = usuarioReg;
      this.fechaMod = fechaMod;
      this.usuarioMod = usuarioMod;
      this.fechaBorrado = fechaBorrado;
      this.usuarioBorrado = usuarioBorrado;
      this.transaccions = transaccions;
   }

   @Id
   @Column(name = "id_tipo_transaccion", unique = true, nullable = false)
   public int getIdTipoTransaccion()
   {
      return this.idTipoTransaccion;
   }

   public void setIdTipoTransaccion(int idTipoTransaccion)
   {
      this.idTipoTransaccion = idTipoTransaccion;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "id_cia", nullable = false)
   public Compania getCompania()
   {
      return this.compania;
   }

   public void setCompania(Compania compania)
   {
      this.compania = compania;
   }

   @Column(name = "nombre", nullable = false, length = 50)
   public String getNombre()
   {
      return this.nombre;
   }

   public void setNombre(String nombre)
   {
      this.nombre = nombre;
   }

   @Column(name = "descripcion", nullable = false, length = 200)
   public String getDescripcion()
   {
      return this.descripcion;
   }

   public void setDescripcion(String descripcion)
   {
      this.descripcion = descripcion;
   }

   @Column(name = "tipo", nullable = false, length = 2)
   public String getTipo()
   {
      return this.tipo;
   }

   public void setTipo(String tipo)
   {
      this.tipo = tipo;
   }

   @Column(name = "flag_estado", length = 2)
   public String getFlagEstado()
   {
      return this.flagEstado;
   }

   public void setFlagEstado(String flagEstado)
   {
      this.flagEstado = flagEstado;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_reg", length = 29)
   public Date getFechaReg()
   {
      return this.fechaReg;
   }

   public void setFechaReg(Date fechaReg)
   {
      this.fechaReg = fechaReg;
   }

   @Column(name = "usuario_reg", length = 30)
   public String getUsuarioReg()
   {
      return this.usuarioReg;
   }

   public void setUsuarioReg(String usuarioReg)
   {
      this.usuarioReg = usuarioReg;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_mod", length = 29)
   public Date getFechaMod()
   {
      return this.fechaMod;
   }

   public void setFechaMod(Date fechaMod)
   {
      this.fechaMod = fechaMod;
   }

   @Column(name = "usuario_mod", length = 30)
   public String getUsuarioMod()
   {
      return this.usuarioMod;
   }

   public void setUsuarioMod(String usuarioMod)
   {
      this.usuarioMod = usuarioMod;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_borrado", length = 29)
   public Date getFechaBorrado()
   {
      return this.fechaBorrado;
   }

   public void setFechaBorrado(Date fechaBorrado)
   {
      this.fechaBorrado = fechaBorrado;
   }

   @Column(name = "usuario_borrado", length = 30)
   public String getUsuarioBorrado()
   {
      return this.usuarioBorrado;
   }

   public void setUsuarioBorrado(String usuarioBorrado)
   {
      this.usuarioBorrado = usuarioBorrado;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoTransaccion")
   public Set<Transaccion> getTransaccions()
   {
      return this.transaccions;
   }

   public void setTransaccions(Set<Transaccion> transaccions)
   {
      this.transaccions = transaccions;
   }

}
