package com.sinapsistech.taxiWeb.model;

// Generated Feb 9, 2015 11:05:15 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Transaccion generated by hbm2java
 */
@Entity
@Table(name = "transaccion"
      , schema = "public")
public class Transaccion implements java.io.Serializable
{

   private int idTransaccion;
   private Carrera carrera;
   private Compania compania;
   private Persona persona;
   private PersonaServicio personaServicio;
   private TipoTransaccion tipoTransaccion;
   private Vehiculo vehiculo;
   private VehiculoAfiliacion vehiculoAfiliacion;
   private Date fechaTransaccion;
   private double montoTotal;
   private String descripcion;
   private Date fechaReg;
   private String usuarioReg;
   private Date fechaMod;
   private String usuarioMod;
   private Date fechaBorrado;
   private String usuarioBorrado;

   public Transaccion()
   {
   }

   public Transaccion(int idTransaccion, Compania compania, Persona persona, TipoTransaccion tipoTransaccion, Date fechaTransaccion, double montoTotal, String descripcion)
   {
      this.idTransaccion = idTransaccion;
      this.compania = compania;
      this.persona = persona;
      this.tipoTransaccion = tipoTransaccion;
      this.fechaTransaccion = fechaTransaccion;
      this.montoTotal = montoTotal;
      this.descripcion = descripcion;
   }

   public Transaccion(int idTransaccion, Carrera carrera, Compania compania, Persona persona, PersonaServicio personaServicio, TipoTransaccion tipoTransaccion, Vehiculo vehiculo, VehiculoAfiliacion vehiculoAfiliacion, Date fechaTransaccion, double montoTotal, String descripcion, Date fechaReg, String usuarioReg, Date fechaMod, String usuarioMod, Date fechaBorrado, String usuarioBorrado)
   {
      this.idTransaccion = idTransaccion;
      this.carrera = carrera;
      this.compania = compania;
      this.persona = persona;
      this.personaServicio = personaServicio;
      this.tipoTransaccion = tipoTransaccion;
      this.vehiculo = vehiculo;
      this.vehiculoAfiliacion = vehiculoAfiliacion;
      this.fechaTransaccion = fechaTransaccion;
      this.montoTotal = montoTotal;
      this.descripcion = descripcion;
      this.fechaReg = fechaReg;
      this.usuarioReg = usuarioReg;
      this.fechaMod = fechaMod;
      this.usuarioMod = usuarioMod;
      this.fechaBorrado = fechaBorrado;
      this.usuarioBorrado = usuarioBorrado;
   }

   @Id
   @Column(name = "id_transaccion", unique = true, nullable = false)
   public int getIdTransaccion()
   {
      return this.idTransaccion;
   }

   public void setIdTransaccion(int idTransaccion)
   {
      this.idTransaccion = idTransaccion;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "id_carrera")
   public Carrera getCarrera()
   {
      return this.carrera;
   }

   public void setCarrera(Carrera carrera)
   {
      this.carrera = carrera;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "id_cia", nullable = false)
   public Compania getCompania()
   {
      return this.compania;
   }

   public void setCompania(Compania compania)
   {
      this.compania = compania;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "id_persona", nullable = false)
   public Persona getPersona()
   {
      return this.persona;
   }

   public void setPersona(Persona persona)
   {
      this.persona = persona;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "id_persona_servicio")
   public PersonaServicio getPersonaServicio()
   {
      return this.personaServicio;
   }

   public void setPersonaServicio(PersonaServicio personaServicio)
   {
      this.personaServicio = personaServicio;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "id_tipo_transaccion", nullable = false)
   public TipoTransaccion getTipoTransaccion()
   {
      return this.tipoTransaccion;
   }

   public void setTipoTransaccion(TipoTransaccion tipoTransaccion)
   {
      this.tipoTransaccion = tipoTransaccion;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "id_vehiculo")
   public Vehiculo getVehiculo()
   {
      return this.vehiculo;
   }

   public void setVehiculo(Vehiculo vehiculo)
   {
      this.vehiculo = vehiculo;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "id_vehiculo_afiliacion")
   public VehiculoAfiliacion getVehiculoAfiliacion()
   {
      return this.vehiculoAfiliacion;
   }

   public void setVehiculoAfiliacion(VehiculoAfiliacion vehiculoAfiliacion)
   {
      this.vehiculoAfiliacion = vehiculoAfiliacion;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_transaccion", nullable = false, length = 29)
   public Date getFechaTransaccion()
   {
      return this.fechaTransaccion;
   }

   public void setFechaTransaccion(Date fechaTransaccion)
   {
      this.fechaTransaccion = fechaTransaccion;
   }

   @Column(name = "monto_total", nullable = false, precision = 17, scale = 17)
   public double getMontoTotal()
   {
      return this.montoTotal;
   }

   public void setMontoTotal(double montoTotal)
   {
      this.montoTotal = montoTotal;
   }

   @Column(name = "descripcion", nullable = false, length = 200)
   public String getDescripcion()
   {
      return this.descripcion;
   }

   public void setDescripcion(String descripcion)
   {
      this.descripcion = descripcion;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_reg", length = 29)
   public Date getFechaReg()
   {
      return this.fechaReg;
   }

   public void setFechaReg(Date fechaReg)
   {
      this.fechaReg = fechaReg;
   }

   @Column(name = "usuario_reg", length = 30)
   public String getUsuarioReg()
   {
      return this.usuarioReg;
   }

   public void setUsuarioReg(String usuarioReg)
   {
      this.usuarioReg = usuarioReg;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_mod", length = 29)
   public Date getFechaMod()
   {
      return this.fechaMod;
   }

   public void setFechaMod(Date fechaMod)
   {
      this.fechaMod = fechaMod;
   }

   @Column(name = "usuario_mod", length = 30)
   public String getUsuarioMod()
   {
      return this.usuarioMod;
   }

   public void setUsuarioMod(String usuarioMod)
   {
      this.usuarioMod = usuarioMod;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_borrado", length = 29)
   public Date getFechaBorrado()
   {
      return this.fechaBorrado;
   }

   public void setFechaBorrado(Date fechaBorrado)
   {
      this.fechaBorrado = fechaBorrado;
   }

   @Column(name = "usuario_borrado", length = 30)
   public String getUsuarioBorrado()
   {
      return this.usuarioBorrado;
   }

   public void setUsuarioBorrado(String usuarioBorrado)
   {
      this.usuarioBorrado = usuarioBorrado;
   }

}
