package com.sinapsistech.taxiWeb.model;

// Generated Feb 9, 2015 11:05:15 AM by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario"
      , schema = "public")
public class Usuario implements java.io.Serializable
{

   private int idUsuario;
   private Compania compania;
   private String nombreCompleto;
   private String usuarioLogin;
   private String usuarioPassword;
   private String flagLdap;
   private String idioma;
   private String emailUsuario;
   private String telefono;
   private String tipoUsuario;
   private String flagEstado;
   private Date fechaReg;
   private String usuarioReg;
   private Date fechaMod;
   private String usuarioMod;
   private Date fechaBorrado;
   private String usuarioBorrado;
   private String ipUsuario;

   public Usuario()
   {
   }

   public Usuario(int idUsuario, Compania compania, String nombreCompleto, String usuarioLogin, String usuarioPassword)
   {
      this.idUsuario = idUsuario;
      this.compania = compania;
      this.nombreCompleto = nombreCompleto;
      this.usuarioLogin = usuarioLogin;
      this.usuarioPassword = usuarioPassword;
   }

   public Usuario(int idUsuario, Compania compania, String nombreCompleto, String usuarioLogin, String usuarioPassword, String flagLdap, String idioma, String emailUsuario, String telefono, String tipoUsuario, String flagEstado, Date fechaReg, String usuarioReg, Date fechaMod, String usuarioMod, Date fechaBorrado, String usuarioBorrado, String ipUsuario)
   {
      this.idUsuario = idUsuario;
      this.compania = compania;
      this.nombreCompleto = nombreCompleto;
      this.usuarioLogin = usuarioLogin;
      this.usuarioPassword = usuarioPassword;
      this.flagLdap = flagLdap;
      this.idioma = idioma;
      this.emailUsuario = emailUsuario;
      this.telefono = telefono;
      this.tipoUsuario = tipoUsuario;
      this.flagEstado = flagEstado;
      this.fechaReg = fechaReg;
      this.usuarioReg = usuarioReg;
      this.fechaMod = fechaMod;
      this.usuarioMod = usuarioMod;
      this.fechaBorrado = fechaBorrado;
      this.usuarioBorrado = usuarioBorrado;
      this.ipUsuario = ipUsuario;
   }

   @Id
   @GeneratedValue(strategy=GenerationType.IDENTITY)
   @Column(name = "id_usuario", unique = true, nullable = false, insertable=false)
   public int getIdUsuario()
   {
      return this.idUsuario;
   }

   public void setIdUsuario(int idUsuario)
   {
      this.idUsuario = idUsuario;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "id_cia", nullable = false)
   public Compania getCompania()
   {
      return this.compania;
   }

   public void setCompania(Compania compania)
   {
      this.compania = compania;
   }

   @Column(name = "nombre_completo", nullable = false, length = 200)
   public String getNombreCompleto()
   {
      return this.nombreCompleto;
   }

   public void setNombreCompleto(String nombreCompleto)
   {
      this.nombreCompleto = nombreCompleto;
   }

   @Column(name = "usuario_login", nullable = false, length = 30)
   public String getUsuarioLogin()
   {
      return this.usuarioLogin;
   }

   public void setUsuarioLogin(String usuarioLogin)
   {
      this.usuarioLogin = usuarioLogin;
   }

   @Column(name = "usuario_password", nullable = false, length = 100)
   public String getUsuarioPassword()
   {
      return this.usuarioPassword;
   }

   public void setUsuarioPassword(String usuarioPassword)
   {
      this.usuarioPassword = usuarioPassword;
   }

   @Column(name = "flag_ldap", length = 2)
   public String getFlagLdap()
   {
      return this.flagLdap;
   }

   public void setFlagLdap(String flagLdap)
   {
      this.flagLdap = flagLdap;
   }

   @Column(name = "idioma", length = 2)
   public String getIdioma()
   {
      return this.idioma;
   }

   public void setIdioma(String idioma)
   {
      this.idioma = idioma;
   }

   @Column(name = "email_usuario", length = 50)
   public String getEmailUsuario()
   {
      return this.emailUsuario;
   }

   public void setEmailUsuario(String emailUsuario)
   {
      this.emailUsuario = emailUsuario;
   }

   @Column(name = "telefono", length = 20)
   public String getTelefono()
   {
      return this.telefono;
   }

   public void setTelefono(String telefono)
   {
      this.telefono = telefono;
   }

   @Column(name = "tipo_usuario", length = 30)
   public String getTipoUsuario()
   {
      return this.tipoUsuario;
   }

   public void setTipoUsuario(String tipoUsuario)
   {
      this.tipoUsuario = tipoUsuario;
   }

   @Column(name = "flag_estado", length = 2)
   public String getFlagEstado()
   {
      return this.flagEstado;
   }

   public void setFlagEstado(String flagEstado)
   {
      this.flagEstado = flagEstado;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_reg", length = 29)
   public Date getFechaReg()
   {
      return this.fechaReg;
   }

   public void setFechaReg(Date fechaReg)
   {
      this.fechaReg = fechaReg;
   }

   @Column(name = "usuario_reg", length = 30)
   public String getUsuarioReg()
   {
      return this.usuarioReg;
   }

   public void setUsuarioReg(String usuarioReg)
   {
      this.usuarioReg = usuarioReg;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_mod", length = 29)
   public Date getFechaMod()
   {
      return this.fechaMod;
   }

   public void setFechaMod(Date fechaMod)
   {
      this.fechaMod = fechaMod;
   }

   @Column(name = "usuario_mod", length = 30)
   public String getUsuarioMod()
   {
      return this.usuarioMod;
   }

   public void setUsuarioMod(String usuarioMod)
   {
      this.usuarioMod = usuarioMod;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_borrado", length = 29)
   public Date getFechaBorrado()
   {
      return this.fechaBorrado;
   }

   public void setFechaBorrado(Date fechaBorrado)
   {
      this.fechaBorrado = fechaBorrado;
   }

   @Column(name = "usuario_borrado", length = 30)
   public String getUsuarioBorrado()
   {
      return this.usuarioBorrado;
   }

   public void setUsuarioBorrado(String usuarioBorrado)
   {
      this.usuarioBorrado = usuarioBorrado;
   }

   @Column(name = "ip_usuario", length = 20)
   public String getIpUsuario()
   {
      return this.ipUsuario;
   }

   public void setIpUsuario(String ipUsuario)
   {
      this.ipUsuario = ipUsuario;
   }

}
