package com.sinapsistech.taxiWeb.model;

// Generated Feb 9, 2015 11:05:15 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Vehiculo generated by hbm2java
 */
@Entity
@Table(name = "vehiculo"
      , schema = "public")
public class Vehiculo implements java.io.Serializable
{

   private int idVehiculo;
   private Compania compania;
   private TipoVehiculo tipoVehiculo;
   private String placa;
   private String modelo;
   private String marca;
   private String numeroMotor;
   private String numeroChasis;
   private int numeroMovilInterno;
   private String descripcion;
   private Integer capacidadPeso;
   private Integer tamano;
   private String flagEstado;
   private Date fechaReg;
   private String usuarioReg;
   private Date fechaMod;
   private String usuarioMod;
   private Date fechaBorrado;
   private String usuarioBorrado;
   private Set<VehiculoPersona> vehiculoPersonas = new HashSet<VehiculoPersona>(0);
   private Set<Carrera> carreras = new HashSet<Carrera>(0);
   private Set<VehiculoParqueo> vehiculoParqueos = new HashSet<VehiculoParqueo>(0);
   private Set<DetallaPersonaServicio> detallaPersonaServicios = new HashSet<DetallaPersonaServicio>(0);
   private Set<Transaccion> transaccions = new HashSet<Transaccion>(0);
   private Set<VehiculoAfiliacion> vehiculoAfiliacions = new HashSet<VehiculoAfiliacion>(0);

   public Vehiculo()
   {
   }

   public Vehiculo(int idVehiculo, Compania compania, TipoVehiculo tipoVehiculo, String placa, String modelo, String marca, String numeroMotor, String numeroChasis, int numeroMovilInterno)
   {
      this.idVehiculo = idVehiculo;
      this.compania = compania;
      this.tipoVehiculo = tipoVehiculo;
      this.placa = placa;
      this.modelo = modelo;
      this.marca = marca;
      this.numeroMotor = numeroMotor;
      this.numeroChasis = numeroChasis;
      this.numeroMovilInterno = numeroMovilInterno;
   }

   public Vehiculo(int idVehiculo, Compania compania, TipoVehiculo tipoVehiculo, String placa, String modelo, String marca, String numeroMotor, String numeroChasis, int numeroMovilInterno, String descripcion, Integer capacidadPeso, Integer tamano, String flagEstado, Date fechaReg, String usuarioReg, Date fechaMod, String usuarioMod, Date fechaBorrado, String usuarioBorrado, Set<VehiculoPersona> vehiculoPersonas, Set<Carrera> carreras, Set<VehiculoParqueo> vehiculoParqueos, Set<DetallaPersonaServicio> detallaPersonaServicios, Set<Transaccion> transaccions, Set<VehiculoAfiliacion> vehiculoAfiliacions)
   {
      this.idVehiculo = idVehiculo;
      this.compania = compania;
      this.tipoVehiculo = tipoVehiculo;
      this.placa = placa;
      this.modelo = modelo;
      this.marca = marca;
      this.numeroMotor = numeroMotor;
      this.numeroChasis = numeroChasis;
      this.numeroMovilInterno = numeroMovilInterno;
      this.descripcion = descripcion;
      this.capacidadPeso = capacidadPeso;
      this.tamano = tamano;
      this.flagEstado = flagEstado;
      this.fechaReg = fechaReg;
      this.usuarioReg = usuarioReg;
      this.fechaMod = fechaMod;
      this.usuarioMod = usuarioMod;
      this.fechaBorrado = fechaBorrado;
      this.usuarioBorrado = usuarioBorrado;
      this.vehiculoPersonas = vehiculoPersonas;
      this.carreras = carreras;
      this.vehiculoParqueos = vehiculoParqueos;
      this.detallaPersonaServicios = detallaPersonaServicios;
      this.transaccions = transaccions;
      this.vehiculoAfiliacions = vehiculoAfiliacions;
   }

   @Id
   @Column(name = "id_vehiculo", unique = true, nullable = false)
   public int getIdVehiculo()
   {
      return this.idVehiculo;
   }

   public void setIdVehiculo(int idVehiculo)
   {
      this.idVehiculo = idVehiculo;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "id_cia", nullable = false)
   public Compania getCompania()
   {
      return this.compania;
   }

   public void setCompania(Compania compania)
   {
      this.compania = compania;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "id_tipo_vehiculo", nullable = false)
   public TipoVehiculo getTipoVehiculo()
   {
      return this.tipoVehiculo;
   }

   public void setTipoVehiculo(TipoVehiculo tipoVehiculo)
   {
      this.tipoVehiculo = tipoVehiculo;
   }

   @Column(name = "placa", nullable = false, length = 10)
   public String getPlaca()
   {
      return this.placa;
   }

   public void setPlaca(String placa)
   {
      this.placa = placa;
   }

   @Column(name = "modelo", nullable = false, length = 20)
   public String getModelo()
   {
      return this.modelo;
   }

   public void setModelo(String modelo)
   {
      this.modelo = modelo;
   }

   @Column(name = "marca", nullable = false, length = 20)
   public String getMarca()
   {
      return this.marca;
   }

   public void setMarca(String marca)
   {
      this.marca = marca;
   }

   @Column(name = "numero_motor", nullable = false, length = 20)
   public String getNumeroMotor()
   {
      return this.numeroMotor;
   }

   public void setNumeroMotor(String numeroMotor)
   {
      this.numeroMotor = numeroMotor;
   }

   @Column(name = "numero_chasis", nullable = false, length = 20)
   public String getNumeroChasis()
   {
      return this.numeroChasis;
   }

   public void setNumeroChasis(String numeroChasis)
   {
      this.numeroChasis = numeroChasis;
   }

   @Column(name = "numero_movil_interno", nullable = false)
   public int getNumeroMovilInterno()
   {
      return this.numeroMovilInterno;
   }

   public void setNumeroMovilInterno(int numeroMovilInterno)
   {
      this.numeroMovilInterno = numeroMovilInterno;
   }

   @Column(name = "descripcion", length = 200)
   public String getDescripcion()
   {
      return this.descripcion;
   }

   public void setDescripcion(String descripcion)
   {
      this.descripcion = descripcion;
   }

   @Column(name = "capacidad_peso")
   public Integer getCapacidadPeso()
   {
      return this.capacidadPeso;
   }

   public void setCapacidadPeso(Integer capacidadPeso)
   {
      this.capacidadPeso = capacidadPeso;
   }

   @Column(name = "tamano")
   public Integer getTamano()
   {
      return this.tamano;
   }

   public void setTamano(Integer tamano)
   {
      this.tamano = tamano;
   }

   @Column(name = "flag_estado", length = 2)
   public String getFlagEstado()
   {
      return this.flagEstado;
   }

   public void setFlagEstado(String flagEstado)
   {
      this.flagEstado = flagEstado;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_reg", length = 29)
   public Date getFechaReg()
   {
      return this.fechaReg;
   }

   public void setFechaReg(Date fechaReg)
   {
      this.fechaReg = fechaReg;
   }

   @Column(name = "usuario_reg", length = 30)
   public String getUsuarioReg()
   {
      return this.usuarioReg;
   }

   public void setUsuarioReg(String usuarioReg)
   {
      this.usuarioReg = usuarioReg;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_mod", length = 29)
   public Date getFechaMod()
   {
      return this.fechaMod;
   }

   public void setFechaMod(Date fechaMod)
   {
      this.fechaMod = fechaMod;
   }

   @Column(name = "usuario_mod", length = 30)
   public String getUsuarioMod()
   {
      return this.usuarioMod;
   }

   public void setUsuarioMod(String usuarioMod)
   {
      this.usuarioMod = usuarioMod;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_borrado", length = 29)
   public Date getFechaBorrado()
   {
      return this.fechaBorrado;
   }

   public void setFechaBorrado(Date fechaBorrado)
   {
      this.fechaBorrado = fechaBorrado;
   }

   @Column(name = "usuario_borrado", length = 30)
   public String getUsuarioBorrado()
   {
      return this.usuarioBorrado;
   }

   public void setUsuarioBorrado(String usuarioBorrado)
   {
      this.usuarioBorrado = usuarioBorrado;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "vehiculo")
   public Set<VehiculoPersona> getVehiculoPersonas()
   {
      return this.vehiculoPersonas;
   }

   public void setVehiculoPersonas(Set<VehiculoPersona> vehiculoPersonas)
   {
      this.vehiculoPersonas = vehiculoPersonas;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "vehiculo")
   public Set<Carrera> getCarreras()
   {
      return this.carreras;
   }

   public void setCarreras(Set<Carrera> carreras)
   {
      this.carreras = carreras;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "vehiculo")
   public Set<VehiculoParqueo> getVehiculoParqueos()
   {
      return this.vehiculoParqueos;
   }

   public void setVehiculoParqueos(Set<VehiculoParqueo> vehiculoParqueos)
   {
      this.vehiculoParqueos = vehiculoParqueos;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "vehiculo")
   public Set<DetallaPersonaServicio> getDetallaPersonaServicios()
   {
      return this.detallaPersonaServicios;
   }

   public void setDetallaPersonaServicios(Set<DetallaPersonaServicio> detallaPersonaServicios)
   {
      this.detallaPersonaServicios = detallaPersonaServicios;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "vehiculo")
   public Set<Transaccion> getTransaccions()
   {
      return this.transaccions;
   }

   public void setTransaccions(Set<Transaccion> transaccions)
   {
      this.transaccions = transaccions;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "vehiculo")
   public Set<VehiculoAfiliacion> getVehiculoAfiliacions()
   {
      return this.vehiculoAfiliacions;
   }

   public void setVehiculoAfiliacions(Set<VehiculoAfiliacion> vehiculoAfiliacions)
   {
      this.vehiculoAfiliacions = vehiculoAfiliacions;
   }

}
