package com.sinapsistech.taxiWeb.model;

// Generated Feb 9, 2015 11:05:15 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VehiculoAfiliacion generated by hbm2java
 */
@Entity
@Table(name = "vehiculo_afiliacion"
      , schema = "public")
public class VehiculoAfiliacion implements java.io.Serializable
{

   private int idVehiculoAfiliacion;
   private Compania compania;
   private Persona persona;
   private Vehiculo vehiculo;
   private Date fechaAfiliacion;
   private double monto;
   private String descripcion;
   private Boolean flagReglamento;
   private Boolean flagEquipoComunicacion;
   private String flagEstado;
   private Date fechaReg;
   private String usuarioReg;
   private Date fechaMod;
   private String usuarioMod;
   private Date fechaBorrado;
   private String usuarioBorrado;
   private Set<Transaccion> transaccions = new HashSet<Transaccion>(0);

   public VehiculoAfiliacion()
   {
   }

   public VehiculoAfiliacion(int idVehiculoAfiliacion, Compania compania, Persona persona, Vehiculo vehiculo, Date fechaAfiliacion, double monto)
   {
      this.idVehiculoAfiliacion = idVehiculoAfiliacion;
      this.compania = compania;
      this.persona = persona;
      this.vehiculo = vehiculo;
      this.fechaAfiliacion = fechaAfiliacion;
      this.monto = monto;
   }

   public VehiculoAfiliacion(int idVehiculoAfiliacion, Compania compania, Persona persona, Vehiculo vehiculo, Date fechaAfiliacion, double monto, String descripcion, Boolean flagReglamento, Boolean flagEquipoComunicacion, String flagEstado, Date fechaReg, String usuarioReg, Date fechaMod, String usuarioMod, Date fechaBorrado, String usuarioBorrado, Set<Transaccion> transaccions)
   {
      this.idVehiculoAfiliacion = idVehiculoAfiliacion;
      this.compania = compania;
      this.persona = persona;
      this.vehiculo = vehiculo;
      this.fechaAfiliacion = fechaAfiliacion;
      this.monto = monto;
      this.descripcion = descripcion;
      this.flagReglamento = flagReglamento;
      this.flagEquipoComunicacion = flagEquipoComunicacion;
      this.flagEstado = flagEstado;
      this.fechaReg = fechaReg;
      this.usuarioReg = usuarioReg;
      this.fechaMod = fechaMod;
      this.usuarioMod = usuarioMod;
      this.fechaBorrado = fechaBorrado;
      this.usuarioBorrado = usuarioBorrado;
      this.transaccions = transaccions;
   }

   @Id
   @GeneratedValue(strategy=GenerationType.IDENTITY)
   @Column(name = "id_vehiculo_afiliacion", unique = true, nullable = false, insertable=false)
   public int getIdVehiculoAfiliacion()
   {
      return this.idVehiculoAfiliacion;
   }

   public void setIdVehiculoAfiliacion(int idVehiculoAfiliacion)
   {
      this.idVehiculoAfiliacion = idVehiculoAfiliacion;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "id_cia", nullable = false)
   public Compania getCompania()
   {
      return this.compania;
   }

   public void setCompania(Compania compania)
   {
      this.compania = compania;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "id_persona", nullable = false)
   public Persona getPersona()
   {
      return this.persona;
   }

   public void setPersona(Persona persona)
   {
      this.persona = persona;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "id_vehiculo", nullable = false)
   public Vehiculo getVehiculo()
   {
      return this.vehiculo;
   }

   public void setVehiculo(Vehiculo vehiculo)
   {
      this.vehiculo = vehiculo;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_afiliacion", nullable = false, length = 29)
   public Date getFechaAfiliacion()
   {
      return this.fechaAfiliacion;
   }

   public void setFechaAfiliacion(Date fechaAfiliacion)
   {
      this.fechaAfiliacion = fechaAfiliacion;
   }

   @Column(name = "monto", nullable = false, precision = 17, scale = 17)
   public double getMonto()
   {
      return this.monto;
   }

   public void setMonto(double monto)
   {
      this.monto = monto;
   }

   @Column(name = "descripcion")
   public String getDescripcion()
   {
      return this.descripcion;
   }

   public void setDescripcion(String descripcion)
   {
      this.descripcion = descripcion;
   }

   @Column(name = "flag_reglamento")
   public Boolean getFlagReglamento()
   {
      return this.flagReglamento;
   }

   public void setFlagReglamento(Boolean flagReglamento)
   {
      this.flagReglamento = flagReglamento;
   }

   @Column(name = "flag_equipo_comunicacion")
   public Boolean getFlagEquipoComunicacion()
   {
      return this.flagEquipoComunicacion;
   }

   public void setFlagEquipoComunicacion(Boolean flagEquipoComunicacion)
   {
      this.flagEquipoComunicacion = flagEquipoComunicacion;
   }

   @Column(name = "flag_estado", length = 2)
   public String getFlagEstado()
   {
      return this.flagEstado;
   }

   public void setFlagEstado(String flagEstado)
   {
      this.flagEstado = flagEstado;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_reg", length = 29)
   public Date getFechaReg()
   {
      return this.fechaReg;
   }

   public void setFechaReg(Date fechaReg)
   {
      this.fechaReg = fechaReg;
   }

   @Column(name = "usuario_reg", length = 30)
   public String getUsuarioReg()
   {
      return this.usuarioReg;
   }

   public void setUsuarioReg(String usuarioReg)
   {
      this.usuarioReg = usuarioReg;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_mod", length = 29)
   public Date getFechaMod()
   {
      return this.fechaMod;
   }

   public void setFechaMod(Date fechaMod)
   {
      this.fechaMod = fechaMod;
   }

   @Column(name = "usuario_mod", length = 30)
   public String getUsuarioMod()
   {
      return this.usuarioMod;
   }

   public void setUsuarioMod(String usuarioMod)
   {
      this.usuarioMod = usuarioMod;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_borrado", length = 29)
   public Date getFechaBorrado()
   {
      return this.fechaBorrado;
   }

   public void setFechaBorrado(Date fechaBorrado)
   {
      this.fechaBorrado = fechaBorrado;
   }

   @Column(name = "usuario_borrado", length = 30)
   public String getUsuarioBorrado()
   {
      return this.usuarioBorrado;
   }

   public void setUsuarioBorrado(String usuarioBorrado)
   {
      this.usuarioBorrado = usuarioBorrado;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "vehiculoAfiliacion")
   public Set<Transaccion> getTransaccions()
   {
      return this.transaccions;
   }

   public void setTransaccions(Set<Transaccion> transaccions)
   {
      this.transaccions = transaccions;
   }

}
