package com.sinapsistech.taxiWeb.model;

// Generated Feb 9, 2015 11:05:15 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VehiculoParqueo generated by hbm2java
 */
@Entity
@Table(name = "vehiculo_parqueo"
      , schema = "public")
public class VehiculoParqueo implements java.io.Serializable
{

   private int idVehiculoParqueo;
   private Compania compania;
   private Parqueo parqueo;
   private Vehiculo vehiculo;
   private Date fechaIngreso;
   private String flagEstado;
   private Date fechaReg;
   private String usuarioReg;
   private Date fechaMod;
   private String usuarioMod;
   private Date fechaBorrado;
   private String usuarioBorrado;

   public VehiculoParqueo()
   {
   }

   public VehiculoParqueo(int idVehiculoParqueo, Compania compania, Parqueo parqueo, Vehiculo vehiculo, Date fechaIngreso)
   {
      this.idVehiculoParqueo = idVehiculoParqueo;
      this.compania = compania;
      this.parqueo = parqueo;
      this.vehiculo = vehiculo;
      this.fechaIngreso = fechaIngreso;
   }

   public VehiculoParqueo(int idVehiculoParqueo, Compania compania, Parqueo parqueo, Vehiculo vehiculo, Date fechaIngreso, String flagEstado, Date fechaReg, String usuarioReg, Date fechaMod, String usuarioMod, Date fechaBorrado, String usuarioBorrado)
   {
      this.idVehiculoParqueo = idVehiculoParqueo;
      this.compania = compania;
      this.parqueo = parqueo;
      this.vehiculo = vehiculo;
      this.fechaIngreso = fechaIngreso;
      this.flagEstado = flagEstado;
      this.fechaReg = fechaReg;
      this.usuarioReg = usuarioReg;
      this.fechaMod = fechaMod;
      this.usuarioMod = usuarioMod;
      this.fechaBorrado = fechaBorrado;
      this.usuarioBorrado = usuarioBorrado;
   }

   @Id
   @Column(name = "id_vehiculo_parqueo", unique = true, nullable = false)
   public int getIdVehiculoParqueo()
   {
      return this.idVehiculoParqueo;
   }

   public void setIdVehiculoParqueo(int idVehiculoParqueo)
   {
      this.idVehiculoParqueo = idVehiculoParqueo;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "id_cia", nullable = false)
   public Compania getCompania()
   {
      return this.compania;
   }

   public void setCompania(Compania compania)
   {
      this.compania = compania;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "id_parqueo", nullable = false)
   public Parqueo getParqueo()
   {
      return this.parqueo;
   }

   public void setParqueo(Parqueo parqueo)
   {
      this.parqueo = parqueo;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "id_vehiculo", nullable = false)
   public Vehiculo getVehiculo()
   {
      return this.vehiculo;
   }

   public void setVehiculo(Vehiculo vehiculo)
   {
      this.vehiculo = vehiculo;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_ingreso", nullable = false, length = 29)
   public Date getFechaIngreso()
   {
      return this.fechaIngreso;
   }

   public void setFechaIngreso(Date fechaIngreso)
   {
      this.fechaIngreso = fechaIngreso;
   }

   @Column(name = "flag_estado", length = 2)
   public String getFlagEstado()
   {
      return this.flagEstado;
   }

   public void setFlagEstado(String flagEstado)
   {
      this.flagEstado = flagEstado;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_reg", length = 29)
   public Date getFechaReg()
   {
      return this.fechaReg;
   }

   public void setFechaReg(Date fechaReg)
   {
      this.fechaReg = fechaReg;
   }

   @Column(name = "usuario_reg", length = 30)
   public String getUsuarioReg()
   {
      return this.usuarioReg;
   }

   public void setUsuarioReg(String usuarioReg)
   {
      this.usuarioReg = usuarioReg;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_mod", length = 29)
   public Date getFechaMod()
   {
      return this.fechaMod;
   }

   public void setFechaMod(Date fechaMod)
   {
      this.fechaMod = fechaMod;
   }

   @Column(name = "usuario_mod", length = 30)
   public String getUsuarioMod()
   {
      return this.usuarioMod;
   }

   public void setUsuarioMod(String usuarioMod)
   {
      this.usuarioMod = usuarioMod;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_borrado", length = 29)
   public Date getFechaBorrado()
   {
      return this.fechaBorrado;
   }

   public void setFechaBorrado(Date fechaBorrado)
   {
      this.fechaBorrado = fechaBorrado;
   }

   @Column(name = "usuario_borrado", length = 30)
   public String getUsuarioBorrado()
   {
      return this.usuarioBorrado;
   }

   public void setUsuarioBorrado(String usuarioBorrado)
   {
      this.usuarioBorrado = usuarioBorrado;
   }

}
