package com.sinapsistech.taxiWeb.model;

// Generated Feb 9, 2015 11:05:15 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VehiculoPersona generated by hbm2java
 */
@Entity
@Table(name = "vehiculo_persona"
      , schema = "public")
public class VehiculoPersona implements java.io.Serializable
{

   private int idVehiculoPersona;
   private Compania compania;
   private Persona personaByIdChofer;
   private Persona personaByIdPersona;
   private Vehiculo vehiculo;
   private Date fechaInicio;
   private Date fechaFin;
   private String flagEstado;
   private Date fechaReg;
   private String usuarioReg;
   private Date fechaMod;
   private String usuarioMod;
   private Date fechaBorrado;
   private String usuarioBorrado;

   public VehiculoPersona()
   {
   }

   public VehiculoPersona(int idVehiculoPersona, Compania compania, Persona personaByIdChofer, Persona personaByIdPersona, Vehiculo vehiculo, Date fechaInicio)
   {
      this.idVehiculoPersona = idVehiculoPersona;
      this.compania = compania;
      this.personaByIdChofer = personaByIdChofer;
      this.personaByIdPersona = personaByIdPersona;
      this.vehiculo = vehiculo;
      this.fechaInicio = fechaInicio;
   }

   public VehiculoPersona(int idVehiculoPersona, Compania compania, Persona personaByIdChofer, Persona personaByIdPersona, Vehiculo vehiculo, Date fechaInicio, Date fechaFin, String flagEstado, Date fechaReg, String usuarioReg, Date fechaMod, String usuarioMod, Date fechaBorrado, String usuarioBorrado)
   {
      this.idVehiculoPersona = idVehiculoPersona;
      this.compania = compania;
      this.personaByIdChofer = personaByIdChofer;
      this.personaByIdPersona = personaByIdPersona;
      this.vehiculo = vehiculo;
      this.fechaInicio = fechaInicio;
      this.fechaFin = fechaFin;
      this.flagEstado = flagEstado;
      this.fechaReg = fechaReg;
      this.usuarioReg = usuarioReg;
      this.fechaMod = fechaMod;
      this.usuarioMod = usuarioMod;
      this.fechaBorrado = fechaBorrado;
      this.usuarioBorrado = usuarioBorrado;
   }

   @Id
   @Column(name = "id_vehiculo_persona", unique = true, nullable = false)
   public int getIdVehiculoPersona()
   {
      return this.idVehiculoPersona;
   }

   public void setIdVehiculoPersona(int idVehiculoPersona)
   {
      this.idVehiculoPersona = idVehiculoPersona;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "id_cia", nullable = false)
   public Compania getCompania()
   {
      return this.compania;
   }

   public void setCompania(Compania compania)
   {
      this.compania = compania;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "id_chofer", nullable = false)
   public Persona getPersonaByIdChofer()
   {
      return this.personaByIdChofer;
   }

   public void setPersonaByIdChofer(Persona personaByIdChofer)
   {
      this.personaByIdChofer = personaByIdChofer;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "id_persona", nullable = false)
   public Persona getPersonaByIdPersona()
   {
      return this.personaByIdPersona;
   }

   public void setPersonaByIdPersona(Persona personaByIdPersona)
   {
      this.personaByIdPersona = personaByIdPersona;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "id_vehiculo", nullable = false)
   public Vehiculo getVehiculo()
   {
      return this.vehiculo;
   }

   public void setVehiculo(Vehiculo vehiculo)
   {
      this.vehiculo = vehiculo;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_inicio", nullable = false, length = 29)
   public Date getFechaInicio()
   {
      return this.fechaInicio;
   }

   public void setFechaInicio(Date fechaInicio)
   {
      this.fechaInicio = fechaInicio;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_fin", length = 29)
   public Date getFechaFin()
   {
      return this.fechaFin;
   }

   public void setFechaFin(Date fechaFin)
   {
      this.fechaFin = fechaFin;
   }

   @Column(name = "flag_estado", length = 2)
   public String getFlagEstado()
   {
      return this.flagEstado;
   }

   public void setFlagEstado(String flagEstado)
   {
      this.flagEstado = flagEstado;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_reg", length = 29)
   public Date getFechaReg()
   {
      return this.fechaReg;
   }

   public void setFechaReg(Date fechaReg)
   {
      this.fechaReg = fechaReg;
   }

   @Column(name = "usuario_reg", length = 30)
   public String getUsuarioReg()
   {
      return this.usuarioReg;
   }

   public void setUsuarioReg(String usuarioReg)
   {
      this.usuarioReg = usuarioReg;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_mod", length = 29)
   public Date getFechaMod()
   {
      return this.fechaMod;
   }

   public void setFechaMod(Date fechaMod)
   {
      this.fechaMod = fechaMod;
   }

   @Column(name = "usuario_mod", length = 30)
   public String getUsuarioMod()
   {
      return this.usuarioMod;
   }

   public void setUsuarioMod(String usuarioMod)
   {
      this.usuarioMod = usuarioMod;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "fecha_borrado", length = 29)
   public Date getFechaBorrado()
   {
      return this.fechaBorrado;
   }

   public void setFechaBorrado(Date fechaBorrado)
   {
      this.fechaBorrado = fechaBorrado;
   }

   @Column(name = "usuario_borrado", length = 30)
   public String getUsuarioBorrado()
   {
      return this.usuarioBorrado;
   }

   public void setUsuarioBorrado(String usuarioBorrado)
   {
      this.usuarioBorrado = usuarioBorrado;
   }

}
